first_names = ["Ezequiel", "Bruno", "Bruna", "Nala", "Santiago", "Waika", "Luis", "Luiz", "David", "Ray", "Dexter",
               "Eduardo", "Nicolly", "Cecília", "Leticia", "Camila", "Vitoria", "Vitória", "Jéssica", "Ana", "Patrick",
               "Lincoln", "Lucas", "Luis Otávio", "Lucas Kenji", "Otávio", "Mariana", "Mariane", "Mick", "Mike", "Eric",
               "Guilherme", "Marcos", "Elvis", "Freddy", "André", "Talia", "Talita", "Fernanda", "Fernando", "Andressa",
               "Amanda", "Tiffany", "Carly", "Nolan", "Gustavo", "Ayrton", "Gabriel", "Gabriele", "Lester", "Pablo",
               "Carla", "Gabby", "Wesley", "Cristina", "Cristian", "Carlos", "Ivone", "Heitor", "Rubens", "Miguel",
               "Helena", "Gael", "Arthur", "Alice", "Davi", "Laura", "Theo", "Nicollas", "Leonardo", "Henrique",
               "Paulo", "Hortência", "Sophia", "Lorenzo", "Enzo", "Valentina", "Lorenzo", "Isabella", "Benjamin",
               "Olivia", "Manuela", "Letácio", "Eloá", "Matheus", "Lívia", "Pedro", "Antônio", "Antônia", "Ana",
               "Daniel", "Danilo", "Felipe", "Clara", "Vitor", "Victor", "Leonardo", "Beatriz", "João", "Bernardo",
               "Sophie", "Isabel", "Luiza", "Murillo", "Murilo", "Carol", "Carolina", "Caroline", "Isis", "Bianca",
               "Miguel", "Saulo", "Larissa", "Manuela", "Caio", "Marlene", "Natália", "Renato", "Ricardo", "Aline",
               "Mirella", "Sandra", "Allan", "Silvio", "Maycon", "Thaís", "Júlia", "Elenice", "Ray", "Cintia", "Jorge",
               "Alan", "Neil", "Liza", "Adam", "Ben", "Berry", "Robert", "Arnold", "Justin", "Federico",
               "Fred", "Leandro", "Lauturo", "Samuel", "Sean", "Arismar", "Helcio", "Paulo", "Ivan", "Iraí", "Charlie",
               "Matilda", "Kirk", "Brian", "Rob", "Deena", "Denver", "Tony", "Renan", "Ellon", "Donald", "Estevão",
               "Paula", "Paulo", "Richard", "Hebert", "Sthefany", "Thiago", "Taína", "Milena", "Monica", "Jonatas",
               "João", "John", "Dean", "Sam", "Igor", "Yuri", "Fadlo", "Rodrigo", "Rafael", "Andy", "André", "Angélica",
               "Brenda", "Sheila", "Kéfera", "Tito", "Kleber", "Emerson", "Jefferson", "Vanessa", "Eric", "Ana Paula",
               "Ana Maria", "Ana Clara", "Marlon", "Ademir", "Odair", "Trevor", "Charles", "Steve", "Charlie", "Bianca",
               "Jack", "Bento", "Beto", "Laís", "Fábio", "Luke", "Anakin", "Alexandre", "Douglas", "Stan", "Priscila",
               "Thomas", "Sérgio", "Vincent", "Paul", "Wanda", "Arthur", "Owen", "Yasmin", "Mabel", "Fiona", "Rachel",
               "Harvey", "Tylor", "Julio", "Julia Castro", "Julia Santos", "Luis António", "Ana Carolina",
               "Marco António", "Vinicius", "Álvaro", "Raul", "Pedro Augusto"]

last_names = ["SantAna", "Silva", "Medellin", "Schaefer", "Garcia", "Prestupa", "Barchi", "Diniz",
              "Torres", "Branco", "Crews", "Castro", "Russo", "Mendonça", "Sanders", "Still",
              "Rodrigues", "Galesco", "Maria", "Trudeau", "Alencar", "Lucatti", "Aparecida", "Santos",
              "Ferreira", "Assis", "Silva", "Armstrong", "Moro", "Presley", "West", "Affleck", "Allen",
              "Richards", "Button", "Tavares", "Ferrari", "Wong", "Bieber", "Jones", "Lipe", "Cameriere",
              "Blason", "MacDonald", "Buss", "Toledo", "Harper", "Sheen", "Smith", "Hillman", "Turk",
              "Castro", "Lopena", "Hansen", "Ruffalo", "Stark", "Denvers", "Lopez", "Bones", "Turner",
              "Merigue", "Connor", "Musk", "Obama", "Zuckerberg", "Agostino", "Cohen", "Feige", "Navarro",
              "Bullock", "Stallone", "Nogueira", "Zandonadi", "Gregolin", "Gagliardi", "DiTomazzo",
              "Jones", "Escobar", "Miranda", "Andrade", "Winchester", "Morningstar", "Moraes", "Batista",
              "Casado", "Colombo", "Cavalcante", "Brito", "Abreu", "Costa", "Moretto", "Pacheco", "Jabur",
              "Merlim", "Manata", "Briggs", "Decanini", "Celestino", "Bueno", "Souza", "Wendland",
              "Jacquin", "Fogazza", "Rosatto", "Levi", "Donizete", "Esperanto", "Petrozzani", "Belloti",
              "Taschetti", "Araújo", "Rigotto", "Girotto", "Lopes", "Silveira", "Vargas", "Leal",
              "Fonseca", "de Assis", "Porchat", "Gentilli", "Bastos", "Mercury", "Vasconselos", "Spinoza",
              "Álamo", "Skywalker", "de Moraes", "Tesla", "Fiuza", "Freitas", "Almeida", "Rogers",
              "Xavier", "Black", "Nascimento", "Walker", "Diesel", "Jobs", "Martella", "Wilson", "Doi",
              "Martinez", "Denvers", "Carvalho", "Spectre", "Dent", "Swift", "Senna", "Coutinho",
              "Pipolo", "Minas", "dos Santos", "Jordan", "James", "Oliveira", "Pereira"]

symbols = ["", "", "", "_", "."]

locations = [
    {
        "city": "Calgary",
        "region": "Alberta",
        "country": "Canada",
        "address1": "734 7 Ave SW 3rd Floor",
        "address2": "",
        "post_code": "AB T2P 3P8",
        "phone_country_code": "1",
        "phone_area_codes": ["403", "587", "825"],
    },
    {
        "city": "Denver",
        "region": "Colorado",
        "country": "United States",
        "address1": "205 Detroit St #800",
        "address2": "",
        "post_code": "80206",
        "phone_country_code": "1",
        "phone_area_codes": ["303", "720"],
    },
    {
        "city": "Long Island City",
        "region": "New York",
        "country": "United States",
        "address1": "38-60 13th St",
        "address2": "",
        "post_code": "11101",
        "phone_country_code": "1",
        "phone_area_codes": ["212"],
    },
    {
        "city": "Kissimmee",
        "region": "Florida",
        "country": "United States",
        "address1": "5293-5285 Images Cir",
        "address2": "",
        "post_code": "34746",
        "phone_country_code": "1",
        "phone_area_codes": ["239", "305", "321"],
    },
    {
        "city": "Cancún",
        "region": "Quintana Roo",
        "country": "Mexico",
        "address1": "Monte Athos Lote 5, SM 310 MZ 109. Cumbres",
        "address2": "",
        "post_code": "77560",
        "phone_country_code": "52",
        "phone_area_codes": ["998", "983", "984", "987", "997"],
    },
    {
        "city": "Winnipeg",
        "region": "Manitoba",
        "country": "Canada",
        "address1": "20 El Tassi Dr",
        "address2": "",
        "post_code": "MB R3W 0L4",
        "phone_country_code": "1",
        "phone_area_codes": ["204", "431"],
    },
    {
        "city": "Calgary",
        "region": "Alberta",
        "country": "Rocky View",
        "address1": "284 Range Rd",
        "address2": "",
        "post_code": "AB T1X 0J5",
        "phone_country_code": "1",
        "phone_area_codes": ["403", "587", "825"],
    },
    {
        "city": "Assis",
        "region": "Sao Paulo",
        "country": "Brazil",
        "address1": "3777 Rui Barbosa Ave",
        "address2": "",
        "post_code": "19816-000",
        "phone_country_code": "55",
        "phone_area_codes": ["18", "21", "19"],
    },
]
